name: photoview

services:
  dev-ui:
    image: photoview/ui
    profiles:
    - dev
    build:
      context: .
      dockerfile: Dockerfile
      target: prepare-ui
    env_file: ui/example.env
    volumes:
    - .:/app:rw
    ports:
    - 1234:1234
    command:
    - /bin/bash
    - -c
    - |
      npm ci
      npm run mon

  dev-api:
    image: photoview/api
    profiles:
    - dev
    build:
      context: .
      dockerfile: Dockerfile
      target: prepare-api
    env_file: api/example.env
    volumes:
    - .:/app:rw
    ports:
    - 4001:4001
    command:
    - /bin/bash
    - -c
    - |
      source /app/scripts/set_compiler_env.sh 
      reflex -g '*.go' -s -- go run .
