config_version = "0"

exclude_patterns = [
  "*_min.*",
  "*-min.*",
  "*.min.*",
  "**/.yarn/**",
  "**/*.d.ts",
  "**/assets/**",
  "**/bower_components/**",
  "**/build/**",
  "**/cache/**",
  "**/config/**",
  "**/db/**",
  "**/deps/**",
  "**/dist/**",
  "**/extern/**",
  "**/external/**",
  "**/generated/**",
  "**/__generated__/**",
  "**/Godeps/**",
  "**/gradlew/**",
  "**/mvnw/**",
  "**/node_modules/**",
  "**/protos/**",
  "**/seed/**",
  "**/target/**",
  "**/templates/**",
  "**/testdata/**",
  "**/vendor/**",
  "api/graphql/generated.go",
  "api/graphql/models/generated.go",
  "api/dataloader/gen_*.go",
]

test_patterns = [
  "**/test/**",
  "**/spec/**",
  "**/*.test.*",
  "**/*.spec.*",
  "**/*_test.*",
  "**/*_spec.*",
  "**/test_*.*",
  "**/spec_*.*",
]

[smells]
mode = "monitor"

[smells.boolean_logic]
threshold = 5

[smells.nested_control_flow]
threshold = 7

[smells.function_parameters]
threshold = 8

[smells.return_statements]
threshold = 8

[smells.file_complexity]
threshold = 65

[smells.function_complexity]
threshold = 23

[smells.identical_code]
threshold = 20

[smells.similar_code]
threshold = 20

[smells.duplication]
nodes_threshold = 83

[[source]]
name = "default"
default = true


[[plugin]]
name = "actionlint"
mode = "comment"

[[plugin]]
name = "eslint"
version = "8.19.0"
mode = "comment"
package_file = "ui/package.json"
package_filters = ["jest", "prettier", "eslint"]

[[plugin]]
name = "gofmt"
mode = "comment"

[[plugin]]
name = "golangci-lint"
mode = "comment"

[[plugin]]
name = "hadolint"
mode = "comment"

[[plugin]]
name = "osv-scanner"
mode = "monitor"

[[plugin]]
name = "radarlint-go"
mode = "monitor"

[[plugin]]
name = "radarlint-iac"
mode = "monitor"

[[plugin]]
name = "ripgrep"
mode = "comment"

[[plugin]]
name = "shellcheck"
mode = "comment"

[[plugin]]
name = "trivy"
version = "0.69.2"
mode = "monitor"
drivers = [
  "config",
  "fs-vuln",
]

[[plugin]]
name = "trufflehog"
mode = "monitor"

[[plugin]]
name = "zizmor"
mode = "monitor"
