// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type AuthorizeResult struct {
	Success bool    `json:"success"`
	Status  string  `json:"status"`
	Token   *string `json:"token"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	RootPath string `json:"rootPath"`
	Admin    bool   `json:"admin"`
}
