// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type AuthorizeResult struct {
	Success bool    `json:"success"`
	Status  string  `json:"status"`
	Token   *string `json:"token"`
}
