// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloader

import (
	"sync"
	"time"

	"github.com/photoview/photoview/api/graphql/models"
)

// AlbumGrantLoader batches and caches requests
type AlbumGrantLoader struct {
	// this method provides the data for the loader
	fetch func(keys []models.UserAlbumKey) ([]*models.UserAlbums, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[models.UserAlbumKey]*models.UserAlbums

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *albumGrantLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type albumGrantLoaderBatch struct {
	keys    []models.UserAlbumKey
	data    []*models.UserAlbums
	error   []error
	closing bool
	done    chan struct{}
}

// Load a UserAlbums by key, batching and caching will be applied automatically
func (l *AlbumGrantLoader) Load(key models.UserAlbumKey) (*models.UserAlbums, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a UserAlbums.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *AlbumGrantLoader) LoadThunk(key models.UserAlbumKey) func() (*models.UserAlbums, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (*models.UserAlbums, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &albumGrantLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (*models.UserAlbums, error) {
		<-batch.done

		var data *models.UserAlbums
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *AlbumGrantLoader) LoadAll(keys []models.UserAlbumKey) ([]*models.UserAlbums, []error) {
	results := make([]func() (*models.UserAlbums, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	userAlbumss := make([]*models.UserAlbums, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		userAlbumss[i], errors[i] = thunk()
	}
	return userAlbumss, errors
}

// LoadAllThunk returns a function that when called will block waiting for a UserAlbumss.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *AlbumGrantLoader) LoadAllThunk(keys []models.UserAlbumKey) func() ([]*models.UserAlbums, []error) {
	results := make([]func() (*models.UserAlbums, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]*models.UserAlbums, []error) {
		userAlbumss := make([]*models.UserAlbums, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			userAlbumss[i], errors[i] = thunk()
		}
		return userAlbumss, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *AlbumGrantLoader) Prime(key models.UserAlbumKey, value *models.UserAlbums) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		// make a copy when writing to the cache, its easy to pass a pointer in from a loop var
		// and end up with the whole cache pointing to the same value.
		cpy := *value
		l.unsafeSet(key, &cpy)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *AlbumGrantLoader) Clear(key models.UserAlbumKey) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *AlbumGrantLoader) unsafeSet(key models.UserAlbumKey, value *models.UserAlbums) {
	if l.cache == nil {
		l.cache = map[models.UserAlbumKey]*models.UserAlbums{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *albumGrantLoaderBatch) keyIndex(l *AlbumGrantLoader, key models.UserAlbumKey) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *albumGrantLoaderBatch) startTimer(l *AlbumGrantLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *albumGrantLoaderBatch) end(l *AlbumGrantLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
