#!/bin/sh
set -eu

cd $(dirname $0)/../api
go generate ./...
if [ "$(git status -s 2>/dev/null | head -1)" != "" ]; then
  echo '--- FAIL: The autogenerated code is out of sync with the recent changes. Please run `go generate ./...` to regenerate it and commit it to this branch.'
  exit 1
fi

echo '--- PASS: All autogenerated code is in sync with the project.'
