package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"

	"github.com/photoview/photoview/api/dataloader"
	api "github.com/photoview/photoview/api/graphql"
	"github.com/photoview/photoview/api/graphql/auth"
	"github.com/photoview/photoview/api/graphql/models"
	"github.com/photoview/photoview/api/graphql/models/actions"
	"gorm.io/gorm"
)

// Media is the resolver for the media field.
func (r *albumResolver) Media(ctx context.Context, obj *models.Album, order *models.Ordering, paginate *models.Pagination, onlyFavorites *bool) ([]*models.Media, error) {
	db := r.DB(ctx)

	query := db.
		Where("media.album_id = ?", obj.ID).
		Where("media.id IN (?)", db.Model(&models.MediaURL{}).
			Select("media_urls.media_id").
			Where("media_urls.media_id = media.id"))

	if onlyFavorites != nil && *onlyFavorites == true {
		user := auth.UserFromContext(ctx)
		if user == nil {
			return nil, errors.New("cannot get favorite media without being authorized")
		}

		favoriteQuery := db.Model(&models.UserMediaData{
			UserID: user.ID,
		}).Where("user_media_data.media_id = media.id").Where("user_media_data.favorite = true")

		query = query.Where("EXISTS (?)", favoriteQuery)
	}

	query = models.FormatSQL(query, order, paginate)

	var media []*models.Media
	if err := query.Find(&media).Error; err != nil {
		return nil, err
	}

	return media, nil
}

// SubAlbums is the resolver for the subAlbums field.
func (r *albumResolver) SubAlbums(ctx context.Context, obj *models.Album, order *models.Ordering, paginate *models.Pagination, showHidden *bool) ([]*models.Album, error) {
	var albums []*models.Album

	db := r.DB(ctx)
	query := db.Where("parent_album_id = ?", obj.ID)

	if user := auth.UserFromContext(ctx); user != nil {
		var err error
		query, err = actions.HiddenAlbumsFilter(showHidden, db, user, query)
		if err != nil {
			return nil, err
		}
	}

	query = models.FormatSQL(query, order, paginate)

	if err := query.Find(&albums).Error; err != nil {
		return nil, err
	}

	return albums, nil
}

// Owner is the resolver for the owner field.
func (r *albumResolver) Owner(ctx context.Context, obj *models.Album) (*models.User, error) {
	panic("not implemented")
}

// ViewerCanUpload is the resolver for the viewerCanUpload field.
func (r *albumResolver) ViewerCanUpload(ctx context.Context, obj *models.Album) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, nil
	}
	if user.Admin {
		return true, nil
	}

	grant, err := dataloader.For(ctx).AlbumGrant.Load(models.UserAlbumKey{UserID: user.ID, AlbumID: obj.ID})
	if err != nil {
		return false, err
	}

	return grant != nil && grant.Level.AtLeast(models.AlbumPermissionLevelUpload), nil
}

// ViewerCanDelete is the resolver for the viewerCanDelete field.
func (r *albumResolver) ViewerCanDelete(ctx context.Context, obj *models.Album) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, nil
	}
	if user.Admin {
		return true, nil
	}

	grant, err := dataloader.For(ctx).AlbumGrant.Load(models.UserAlbumKey{UserID: user.ID, AlbumID: obj.ID})
	if err != nil {
		return false, err
	}

	return grant != nil && grant.Level.AtLeast(models.AlbumPermissionLevelDelete), nil
}

// ViewerIsOwner is the resolver for the viewerIsOwner field.
func (r *albumResolver) ViewerIsOwner(ctx context.Context, obj *models.Album) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, nil
	}
	if user.Admin {
		return true, nil
	}

	grant, err := dataloader.For(ctx).AlbumGrant.Load(models.UserAlbumKey{UserID: user.ID, AlbumID: obj.ID})
	if err != nil {
		return false, err
	}

	return grant != nil && grant.GrantedByUserID == nil, nil
}

// ViewerHidden is the resolver for the viewerHidden field.
func (r *albumResolver) ViewerHidden(ctx context.Context, obj *models.Album) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, nil
	}

	return dataloader.For(ctx).AlbumHidden.Load(&models.UserAlbumData{
		UserID:  user.ID,
		AlbumID: obj.ID,
	})
}

// Thumbnail is the resolver for the thumbnail field.
func (r *albumResolver) Thumbnail(ctx context.Context, obj *models.Album) (*models.Media, error) {
	return obj.Thumbnail(r.DB(ctx))
}

// Path is the resolver for the path field.
func (r *albumResolver) Path(ctx context.Context, obj *models.Album) ([]*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		empty := make([]*models.Album, 0)
		return empty, nil
	}

	return actions.AlbumPath(r.DB(ctx), user, obj)
}

// Shares is the resolver for the shares field.
func (r *albumResolver) Shares(ctx context.Context, obj *models.Album) ([]*models.ShareToken, error) {
	var shareTokens []*models.ShareToken
	if err := r.DB(ctx).Where("album_id = ?", obj.ID).Find(&shareTokens).Error; err != nil {
		return nil, err
	}

	return shareTokens, nil
}

// Permissions is the resolver for the permissions field.
func (r *albumResolver) Permissions(ctx context.Context, obj *models.Album) ([]*models.AlbumPermission, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, nil
	}

	isOwner, err := r.ViewerIsOwner(ctx, obj)
	if err != nil {
		return nil, err
	}
	if !isOwner {
		return nil, nil
	}

	return actions.AlbumPermissions(r.DB(ctx), obj.ID, user.ID)
}

// Takes album_id, resets album.cover_id to 0 (null)
func (r *mutationResolver) ResetAlbumCover(ctx context.Context, albumID int) (*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	return actions.ResetAlbumCover(r.DB(ctx), user, albumID)
}

// SetAlbumCover is the resolver for the setAlbumCover field.
func (r *mutationResolver) SetAlbumCover(ctx context.Context, coverID int) (*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	return actions.SetAlbumCover(r.DB(ctx), user, coverID)
}

// GrantAlbumAccess is the resolver for the grantAlbumAccess field.
func (r *mutationResolver) GrantAlbumAccess(ctx context.Context, albumID int, userID int, level models.AlbumPermissionLevel) (*models.AlbumPermission, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	return actions.GrantAlbumAccess(r.DB(ctx), user, albumID, userID, level)
}

// RevokeAlbumAccess is the resolver for the revokeAlbumAccess field.
func (r *mutationResolver) RevokeAlbumAccess(ctx context.Context, albumID int, userID int) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, auth.ErrUnauthorized
	}

	if err := actions.RevokeAlbumAccess(r.DB(ctx), user, albumID, userID); err != nil {
		return false, err
	}

	return true, nil
}

// HideAlbum is the resolver for the hideAlbum field.
func (r *mutationResolver) HideAlbum(ctx context.Context, albumID int, hidden bool) (*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	return user.HideAlbum(r.DB(ctx), albumID, hidden)
}

// UnhideAllAlbums is the resolver for the unhideAllAlbums field.
func (r *mutationResolver) UnhideAllAlbums(ctx context.Context) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, auth.ErrUnauthorized
	}

	if err := user.UnhideAllAlbums(r.DB(ctx)); err != nil {
		return false, err
	}

	return true, nil
}

// ShareableUsers is the resolver for the shareableUsers field.
func (r *queryResolver) ShareableUsers(ctx context.Context) ([]*models.User, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	var users []*models.User
	if err := r.DB(ctx).Find(&users).Error; err != nil {
		return nil, err
	}

	return users, nil
}

// MyAlbums is the resolver for the myAlbums field.
func (r *queryResolver) MyAlbums(ctx context.Context, order *models.Ordering, paginate *models.Pagination, onlyRoot *bool, showEmpty *bool, onlyWithFavorites *bool, showHidden *bool) ([]*models.Album, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	return actions.MyAlbums(r.DB(ctx), user, order, paginate, onlyRoot, showEmpty, onlyWithFavorites, showHidden)
}

// Album is the resolver for the album field.
func (r *queryResolver) Album(ctx context.Context, id int, tokenCredentials *models.ShareTokenCredentials) (*models.Album, error) {
	db := r.DB(ctx)
	if tokenCredentials != nil {

		shareToken, err := r.ShareToken(ctx, *tokenCredentials)
		if err != nil {
			return nil, err
		}

		if shareToken.Album != nil {
			if *shareToken.AlbumID == id {
				return shareToken.Album, nil
			}

			subAlbum, err := shareToken.Album.GetChildren(db, func(query *gorm.DB) *gorm.DB {
				return query.Where("sub_albums.id = ?", id)
			})
			if err != nil {
				return nil, fmt.Errorf("find sub album of share token (%s): %w", tokenCredentials.Token, err)
			}

			if len(subAlbum) > 0 {
				return subAlbum[0], nil
			}
		}
	}

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	return actions.Album(db, user, id)
}

// Album returns api.AlbumResolver implementation.
func (r *Resolver) Album() api.AlbumResolver { return &albumResolver{r} }

type albumResolver struct{ *Resolver }
