package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/photoview/photoview/api/utils"
)

// GoogleOAuthClientID is the resolver for the googleOAuthClientID field.
func (r *queryResolver) GoogleOAuthClientID(ctx context.Context) (*string, error) {
	clientID := utils.EnvGoogleOAuthClientID.GetValue()
	if clientID == "" {
		return nil, nil
	}

	return &clientID, nil
}
