package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/photoview/photoview/api/graphql/auth"
	"github.com/photoview/photoview/api/graphql/models"
	"github.com/photoview/photoview/api/utils"
	"gorm.io/gorm"
)

// ViewerCanUpload is the resolver for the viewerCanUpload field.
func (r *mediaResolver) ViewerCanUpload(ctx context.Context, obj *models.Media) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, nil
	}

	db := r.DB(ctx)
	var album models.Album
	if err := db.First(&album, obj.AlbumID).Error; err != nil {
		return false, err
	}

	return user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelUpload)
}

// RenameMedia is the resolver for the renameMedia field.
func (r *mutationResolver) RenameMedia(ctx context.Context, mediaID int, newName string) (*models.Media, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	var media models.Media
	if err := db.First(&media, mediaID).Error; err != nil {
		return nil, err
	}

	var album models.Album
	if err := db.First(&album, media.AlbumID).Error; err != nil {
		return nil, err
	}

	canRename, err := user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelUpload)
	if err != nil {
		return nil, err
	}
	if !canRename {
		return nil, auth.ErrUnauthorized
	}

	safeName, err := sanitizeFileName(newName)
	if err != nil {
		return nil, err
	}

	newPath := filepath.Join(filepath.Dir(media.Path), safeName)
	if !utils.IsSubPath(album.Path, newPath) {
		return nil, errors.New("invalid file name")
	}

	if newPath == media.Path {
		return &media, nil
	}

	if _, err := os.Stat(newPath); err == nil {
		return nil, errors.New("a file with that name already exists")
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("could not check destination path: %w", err)
	}

	if err := os.Rename(media.Path, newPath); err != nil {
		return nil, fmt.Errorf("could not rename file on disk: %w", err)
	}

	oldPath := media.Path
	oldSidecarPath := media.SideCarPath

	var newSidecarPath *string
	if media.SideCarPath != nil {
		newBase := strings.TrimSuffix(safeName, filepath.Ext(safeName))
		sidecarName := newBase + filepath.Ext(*media.SideCarPath)
		joined := filepath.Join(filepath.Dir(*media.SideCarPath), sidecarName)
		newSidecarPath = &joined
	}

	transErr := db.Transaction(func(tx *gorm.DB) error {
		if newSidecarPath != nil {
			if err := os.Rename(*oldSidecarPath, *newSidecarPath); err != nil {
				return fmt.Errorf("could not rename sidecar file: %w", err)
			}
			media.SideCarPath = newSidecarPath
			hash := models.MD5Hash(*newSidecarPath)
			media.SideCarHash = &hash
		}

		media.Path = newPath
		media.Title = safeName

		return tx.Save(&media).Error
	})
	if transErr != nil {
		// Best-effort rollback of the filesystem renames so disk and DB
		// don't end up disagreeing about where the files live.
		_ = os.Rename(newPath, oldPath)
		if newSidecarPath != nil && oldSidecarPath != nil {
			_ = os.Rename(*newSidecarPath, *oldSidecarPath)
		}
		return nil, transErr
	}

	return &media, nil
}

// DeleteMedia is the resolver for the deleteMedia field.
func (r *mutationResolver) DeleteMedia(ctx context.Context, mediaID int) (bool, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, auth.ErrUnauthorized
	}

	var media models.Media
	if err := db.First(&media, mediaID).Error; err != nil {
		return false, err
	}

	var album models.Album
	if err := db.First(&album, media.AlbumID).Error; err != nil {
		return false, err
	}

	canDelete, err := user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelUpload)
	if err != nil {
		return false, err
	}
	if !canDelete {
		return false, auth.ErrUnauthorized
	}

	trashDir := filepath.Join(album.Path, ".trash")
	if err := os.MkdirAll(trashDir, 0o755); err != nil {
		return false, fmt.Errorf("could not create trash folder: %w", err)
	}

	timestamp := time.Now().Unix()
	trashPath := filepath.Join(trashDir, fmt.Sprintf("%d-%s", timestamp, filepath.Base(media.Path)))
	if err := os.Rename(media.Path, trashPath); err != nil {
		return false, fmt.Errorf("could not move file to trash: %w", err)
	}

	if media.SideCarPath != nil {
		sidecarTrashPath := filepath.Join(trashDir, fmt.Sprintf("%d-%s", timestamp, filepath.Base(*media.SideCarPath)))
		// Best-effort: the primary file is already safely trashed, and the
		// sidecar isn't required for the library entry to be gone.
		_ = os.Rename(*media.SideCarPath, sidecarTrashPath)
	}

	// MediaURL and ImageFace rows point *at* Media (has-many) and are
	// cascade-deleted below, but the cached thumbnail/highres/web-video
	// files MediaURL points at are not - remove them explicitly,
	// mirroring cleanup_tasks' album-level cache cleanup.
	cacheDir := filepath.Join(utils.MediaCachePath(), strconv.Itoa(media.AlbumID), strconv.Itoa(media.ID))
	_ = os.RemoveAll(cacheDir)

	// MediaEXIF/VideoMetadata are the opposite direction (Media points at
	// them via ExifID/VideoMetadataID), so deleting Media does not cascade
	// to them - delete them explicitly to avoid leaving orphan rows.
	deleteErr := db.Transaction(func(tx *gorm.DB) error {
		if media.ExifID != nil {
			if err := tx.Delete(&models.MediaEXIF{}, *media.ExifID).Error; err != nil {
				return err
			}
		}
		if media.VideoMetadataID != nil {
			if err := tx.Delete(&models.VideoMetadata{}, *media.VideoMetadataID).Error; err != nil {
				return err
			}
		}
		return tx.Delete(&media).Error
	})
	if deleteErr != nil {
		// The file is already in the trash but the DB rows remain -
		// surface the error rather than silently leaving a stale entry.
		return false, fmt.Errorf("moved to trash, but failed to remove library entry: %w", deleteErr)
	}

	return true, nil
}
