package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/photoview/photoview/api/graphql/auth"
	"github.com/photoview/photoview/api/graphql/models"
	"github.com/photoview/photoview/api/utils"
	"gorm.io/gorm"
)

// ViewerCanUpload is the resolver for the viewerCanUpload field.
func (r *mediaResolver) ViewerCanUpload(ctx context.Context, obj *models.Media) (bool, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, nil
	}

	db := r.DB(ctx)
	var album models.Album
	if err := db.First(&album, obj.AlbumID).Error; err != nil {
		return false, err
	}

	return user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelUpload)
}

// RenameMedia is the resolver for the renameMedia field.
func (r *mutationResolver) RenameMedia(ctx context.Context, mediaID int, newName string) (*models.Media, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	var media models.Media
	if err := db.First(&media, mediaID).Error; err != nil {
		return nil, err
	}

	var album models.Album
	if err := db.First(&album, media.AlbumID).Error; err != nil {
		return nil, err
	}

	canRename, err := user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelUpload)
	if err != nil {
		return nil, err
	}
	if !canRename {
		return nil, auth.ErrUnauthorized
	}

	safeName, err := sanitizeFileName(newName)
	if err != nil {
		return nil, err
	}

	newPath := filepath.Join(filepath.Dir(media.Path), safeName)
	if !utils.IsSubPath(album.Path, newPath) {
		return nil, errors.New("invalid file name")
	}

	if newPath == media.Path {
		return &media, nil
	}

	if _, err := os.Stat(newPath); err == nil {
		return nil, errors.New("a file with that name already exists")
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("could not check destination path: %w", err)
	}

	if err := os.Rename(media.Path, newPath); err != nil {
		return nil, fmt.Errorf("could not rename file on disk: %w", err)
	}

	oldPath := media.Path
	oldSidecarPath := media.SideCarPath

	var newSidecarPath *string
	if media.SideCarPath != nil {
		newBase := strings.TrimSuffix(safeName, filepath.Ext(safeName))
		sidecarName := newBase + filepath.Ext(*media.SideCarPath)
		joined := filepath.Join(filepath.Dir(*media.SideCarPath), sidecarName)
		newSidecarPath = &joined
	}

	transErr := db.Transaction(func(tx *gorm.DB) error {
		if newSidecarPath != nil {
			if err := os.Rename(*oldSidecarPath, *newSidecarPath); err != nil {
				return fmt.Errorf("could not rename sidecar file: %w", err)
			}
			media.SideCarPath = newSidecarPath
			hash := models.MD5Hash(*newSidecarPath)
			media.SideCarHash = &hash
		}

		media.Path = newPath
		media.Title = safeName

		return tx.Save(&media).Error
	})
	if transErr != nil {
		// Best-effort rollback of the filesystem renames so disk and DB
		// don't end up disagreeing about where the files live.
		_ = os.Rename(newPath, oldPath)
		if newSidecarPath != nil && oldSidecarPath != nil {
			_ = os.Rename(*newSidecarPath, *oldSidecarPath)
		}
		return nil, transErr
	}

	return &media, nil
}

// DeleteMedia is the resolver for the deleteMedia field.
func (r *mutationResolver) DeleteMedia(ctx context.Context, mediaID int) (bool, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, auth.ErrUnauthorized
	}

	if err := deleteOneMedia(db, user, mediaID); err != nil {
		return false, err
	}

	return true, nil
}

// DeleteMediaList is the resolver for the deleteMediaList field.
func (r *mutationResolver) DeleteMediaList(ctx context.Context, mediaIds []int) ([]*models.DeleteMediaResult, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	results := make([]*models.DeleteMediaResult, 0, len(mediaIds))
	for _, mediaID := range mediaIds {
		result := &models.DeleteMediaResult{MediaID: mediaID, Success: true}
		if err := deleteOneMedia(db, user, mediaID); err != nil {
			result.Success = false
			msg := err.Error()
			result.Error = &msg
		}
		results = append(results, result)
	}

	return results, nil
}
