package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/photoview/photoview/api/database/drivers"
	"github.com/photoview/photoview/api/graphql/auth"
	"github.com/photoview/photoview/api/graphql/models"
	"github.com/photoview/photoview/api/scanner/periodic_scanner"
	"github.com/photoview/photoview/api/scanner/scanner_queue"
	"gorm.io/gorm"
)

// ScanAll is the resolver for the scanAll field.
func (r *mutationResolver) ScanAll(ctx context.Context) (*models.ScannerResult, error) {
	err := scanner_queue.AddAllToQueue()
	if err != nil {
		return nil, err
	}

	startMessage := "Scanner started"

	return &models.ScannerResult{
		Finished: false,
		Success:  true,
		Message:  &startMessage,
	}, nil
}

// ScanUser is the resolver for the scanUser field.
func (r *mutationResolver) ScanUser(ctx context.Context, userID int) (*models.ScannerResult, error) {
	var user models.User
	if err := r.DB(ctx).First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("get user from database: %w", err)
	}

	scanner_queue.AddUserToQueue(&user)

	startMessage := "Scanner started"
	return &models.ScannerResult{
		Finished: false,
		Success:  true,
		Message:  &startMessage,
	}, nil
}

// ScanAlbum is the resolver for the scanAlbum field.
func (r *mutationResolver) ScanAlbum(ctx context.Context, albumID int) (*models.ScannerResult, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	var album models.Album
	if err := db.First(&album, albumID).Error; err != nil {
		return nil, fmt.Errorf("get album from database: %w", err)
	}

	canScan, err := user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelUpload)
	if err != nil {
		return nil, err
	}
	if !canScan {
		return nil, auth.ErrUnauthorized
	}

	if err := addAlbumToQueue(&album); err != nil {
		return nil, err
	}

	startMessage := "Scanner started"
	return &models.ScannerResult{
		Finished: false,
		Success:  true,
		Message:  &startMessage,
	}, nil
}

// CancelScanJob is the resolver for the cancelScanJob field.
func (r *mutationResolver) CancelScanJob(ctx context.Context, albumID int) (bool, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, auth.ErrUnauthorized
	}

	var album models.Album
	if err := db.First(&album, albumID).Error; err != nil {
		return false, fmt.Errorf("get album from database: %w", err)
	}

	canCancel, err := user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelUpload)
	if err != nil {
		return false, err
	}
	if !canCancel {
		return false, auth.ErrUnauthorized
	}

	return cancelScanJob(albumID), nil
}

// SetPeriodicScanInterval is the resolver for the setPeriodicScanInterval field.
func (r *mutationResolver) SetPeriodicScanInterval(ctx context.Context, interval int) (int, error) {
	db := r.DB(ctx)
	if interval < 0 {
		return 0, errors.New("interval must be 0 or above")
	}

	if err := db.
		Session(&gorm.Session{AllowGlobalUpdate: true}).
		Model(&models.SiteInfo{}).
		Update("periodic_scan_interval", interval).
		Error; err != nil {

		return 0, err
	}

	var siteInfo models.SiteInfo
	if err := db.First(&siteInfo).Error; err != nil {
		return 0, err
	}

	periodic_scanner.ChangePeriodicScanInterval(time.Duration(siteInfo.PeriodicScanInterval) * time.Second)

	return siteInfo.PeriodicScanInterval, nil
}

// SetScannerConcurrentWorkers is the resolver for the setScannerConcurrentWorkers field.
func (r *mutationResolver) SetScannerConcurrentWorkers(ctx context.Context, workers int) (int, error) {
	db := r.DB(ctx)
	if workers < 1 {
		return 0, errors.New("concurrent workers must at least be 1")
	}

	if workers > 1 && drivers.DatabaseDriverFromEnv() == drivers.SQLITE {
		return 0, errors.New("multiple workers not supported for SQLite databases")
	}

	if err := db.
		Session(&gorm.Session{AllowGlobalUpdate: true}).
		Model(&models.SiteInfo{}).
		Update("concurrent_workers", workers).
		Error; err != nil {

		return 0, err
	}

	var siteInfo models.SiteInfo
	if err := db.First(&siteInfo).Error; err != nil {
		return 0, err
	}

	scanner_queue.ChangeScannerConcurrentWorkers(siteInfo.ConcurrentWorkers)

	return siteInfo.ConcurrentWorkers, nil
}

// ScannerQueueStatus is the resolver for the scannerQueueStatus field.
func (r *queryResolver) ScannerQueueStatus(ctx context.Context) ([]*models.ScannerQueueItem, error) {
	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, auth.ErrUnauthorized
	}

	items := getScannerQueueStatus()

	if user.Admin {
		result := make([]*models.ScannerQueueItem, len(items))
		for i := range items {
			result[i] = &items[i]
		}
		return result, nil
	}

	db := r.DB(ctx)
	result := make([]*models.ScannerQueueItem, 0, len(items))
	for i := range items {
		canView, err := user.HasAlbumLevel(db, items[i].Album, models.AlbumPermissionLevelRead)
		if err != nil {
			return nil, err
		}
		if canView {
			result = append(result, &items[i])
		}
	}
	return result, nil
}
