package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	api "github.com/photoview/photoview/api/graphql"
	"github.com/photoview/photoview/api/graphql/models"
	"github.com/photoview/photoview/api/scanner/face_detection"
	"github.com/photoview/photoview/api/utils"
	"gorm.io/gorm"
)

// SetMapStyleLight is the resolver for the setMapStyleLight field.
func (r *mutationResolver) SetMapStyleLight(ctx context.Context, url string) (string, error) {
	if err := validateMapStyleURL(url); err != nil {
		return "", err
	}

	db := r.DB(ctx)

	if err := db.
		Session(&gorm.Session{AllowGlobalUpdate: true}).
		Model(&models.SiteInfo{}).
		Update("map_style_light", url).
		Error; err != nil {
		return "", err
	}

	var siteInfo models.SiteInfo
	if err := db.First(&siteInfo).Error; err != nil {
		return "", err
	}

	return siteInfo.MapStyleLight, nil
}

// SetMapStyleDark is the resolver for the setMapStyleDark field.
func (r *mutationResolver) SetMapStyleDark(ctx context.Context, url string) (string, error) {
	if err := validateMapStyleURL(url); err != nil {
		return "", err
	}

	db := r.DB(ctx)

	if err := db.
		Session(&gorm.Session{AllowGlobalUpdate: true}).
		Model(&models.SiteInfo{}).
		Update("map_style_dark", url).
		Error; err != nil {
		return "", err
	}

	var siteInfo models.SiteInfo
	if err := db.First(&siteInfo).Error; err != nil {
		return "", err
	}

	return siteInfo.MapStyleDark, nil
}

// SiteInfo is the resolver for the siteInfo field.
func (r *queryResolver) SiteInfo(ctx context.Context) (*models.SiteInfo, error) {
	return models.GetSiteInfo(r.DB(ctx))
}

// FaceDetectionEnabled is the resolver for the faceDetectionEnabled field.
func (r *siteInfoResolver) FaceDetectionEnabled(ctx context.Context, obj *models.SiteInfo) (bool, error) {
	return face_detection.GlobalFaceDetector != nil, nil
}

// MapEnabled is the resolver for the mapEnabled field.
func (r *siteInfoResolver) MapEnabled(ctx context.Context, obj *models.SiteInfo) (bool, error) {
	return !utils.EnvDisableMap.GetBool(), nil
}

// SiteInfo returns api.SiteInfoResolver implementation.
func (r *Resolver) SiteInfo() api.SiteInfoResolver { return &siteInfoResolver{r} }

type siteInfoResolver struct{ *Resolver }
