package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/photoview/photoview/api/graphql/auth"
	"github.com/photoview/photoview/api/graphql/models"
	"github.com/photoview/photoview/api/utils"
	"gorm.io/gorm"
)

// CreateAlbumFolder is the resolver for the createAlbumFolder field.
func (r *mutationResolver) CreateAlbumFolder(ctx context.Context, parentAlbumID int, name string) (*models.Album, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	var parent models.Album
	if err := db.First(&parent, parentAlbumID).Error; err != nil {
		return nil, err
	}

	canUpload, err := user.HasAlbumLevel(db, &parent, models.AlbumPermissionLevelUpload)
	if err != nil {
		return nil, err
	}
	if !canUpload {
		return nil, errors.New("unauthorized")
	}

	safeName, err := sanitizeFileName(name)
	if err != nil {
		return nil, err
	}

	newPath := filepath.Join(parent.Path, safeName)
	if !utils.IsSubPath(parent.Path, newPath) {
		return nil, errors.New("invalid folder name")
	}

	if err := os.Mkdir(newPath, 0o755); err != nil {
		if os.IsExist(err) {
			return nil, errors.New("a folder with that name already exists")
		}
		return nil, fmt.Errorf("could not create folder: %w", err)
	}

	album := models.Album{
		Title:         safeName,
		ParentAlbumID: &parent.ID,
		Path:          newPath,
	}

	transErr := db.Transaction(func(tx *gorm.DB) error {
		if err := tx.Create(&album).Error; err != nil {
			return err
		}

		// New folders inherit every one of the parent's current grants
		// (level and grantedBy included), not just the uploader, mirroring
		// the scanner's own walkAlbumScanQueue.
		var parentGrants []models.UserAlbums
		if err := tx.Where("album_id = ?", parent.ID).Find(&parentGrants).Error; err != nil {
			return err
		}
		for _, g := range parentGrants {
			g.AlbumID = album.ID
			if err := tx.Create(&g).Error; err != nil {
				return err
			}
		}
		return nil
	})
	if transErr != nil {
		_ = os.Remove(newPath)
		return nil, transErr
	}

	// Best-effort: keeps the scanner's ignore-file cache consistent and picks
	// up anything already sitting in the new folder out-of-band. Not required
	// for correctness since the Album row above already exists.
	_ = addAlbumToQueue(&parent)

	return &album, nil
}

// MoveAlbum is the resolver for the moveAlbum field.
func (r *mutationResolver) MoveAlbum(ctx context.Context, albumID int, newParentAlbumID int) (*models.Album, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return nil, errors.New("unauthorized")
	}

	var album models.Album
	if err := db.First(&album, albumID).Error; err != nil {
		return nil, err
	}

	if album.ParentAlbumID == nil {
		return nil, errors.New("root albums cannot be moved")
	}

	var newParent models.Album
	if err := db.First(&newParent, newParentAlbumID).Error; err != nil {
		return nil, err
	}

	if canDelete, err := user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelDelete); err != nil {
		return nil, err
	} else if !canDelete {
		return nil, errors.New("unauthorized")
	}

	if canUpload, err := user.HasAlbumLevel(db, &newParent, models.AlbumPermissionLevelUpload); err != nil {
		return nil, err
	} else if !canUpload {
		return nil, errors.New("unauthorized")
	}

	// subtree holds the album being moved plus every descendant (the query
	// includes the root of the recursive walk), used both for the cycle
	// check below and for rewriting descendant paths after the move.
	subtree, err := album.GetChildren(db, nil)
	if err != nil {
		return nil, fmt.Errorf("could not resolve album subtree: %w", err)
	}

	for _, a := range subtree {
		if a.ID == newParent.ID {
			return nil, errors.New("cannot move an album into itself or one of its own sub-albums")
		}
	}

	oldPath := album.Path
	newPath := filepath.Join(newParent.Path, album.Title)

	if !utils.IsSubPath(newParent.Path, newPath) {
		return nil, errors.New("invalid album title for the destination path")
	}

	if _, err := os.Stat(newPath); err == nil {
		return nil, errors.New("a folder with that name already exists in the destination")
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("could not check destination path: %w", err)
	}

	var descendantMedia []models.Media
	if err := db.Where("album_id IN (?)", albumIDs(subtree)).Find(&descendantMedia).Error; err != nil {
		return nil, fmt.Errorf("could not load media to move: %w", err)
	}

	if err := os.Rename(oldPath, newPath); err != nil {
		return nil, fmt.Errorf("could not move folder on disk: %w", err)
	}

	transErr := db.Transaction(func(tx *gorm.DB) error {
		for _, a := range subtree {
			a.Path = strings.Replace(a.Path, oldPath, newPath, 1)
			if a.ID == album.ID {
				a.ParentAlbumID = &newParent.ID
			}
			if err := tx.Save(a).Error; err != nil {
				return err
			}
		}

		for _, m := range descendantMedia {
			m.Path = strings.Replace(m.Path, oldPath, newPath, 1)
			if m.SideCarPath != nil {
				replaced := strings.Replace(*m.SideCarPath, oldPath, newPath, 1)
				m.SideCarPath = &replaced
			}
			if err := tx.Save(&m).Error; err != nil {
				return err
			}
		}

		return nil
	})
	if transErr != nil {
		// Best-effort rollback of the filesystem move so disk and DB don't
		// end up disagreeing about where the folder lives.
		_ = os.Rename(newPath, oldPath)
		return nil, transErr
	}

	_ = addAlbumToQueue(&newParent)

	album.Path = newPath
	album.ParentAlbumID = &newParent.ID
	return &album, nil
}

// DeleteAlbum is the resolver for the deleteAlbum field.
func (r *mutationResolver) DeleteAlbum(ctx context.Context, albumID int) (bool, error) {
	db := r.DB(ctx)

	user := auth.UserFromContext(ctx)
	if user == nil {
		return false, errors.New("unauthorized")
	}

	var album models.Album
	if err := db.First(&album, albumID).Error; err != nil {
		return false, err
	}

	if album.ParentAlbumID == nil {
		return false, errors.New("root albums cannot be deleted")
	}

	var parent models.Album
	if err := db.First(&parent, *album.ParentAlbumID).Error; err != nil {
		return false, err
	}

	canDelete, err := user.HasAlbumLevel(db, &album, models.AlbumPermissionLevelDelete)
	if err != nil {
		return false, err
	}
	if !canDelete {
		return false, errors.New("unauthorized")
	}

	subtree, err := album.GetChildren(db, nil)
	if err != nil {
		return false, fmt.Errorf("could not resolve album subtree: %w", err)
	}

	trashDir := filepath.Join(parent.Path, ".trash")
	if err := os.MkdirAll(trashDir, 0o755); err != nil {
		return false, fmt.Errorf("could not create trash folder: %w", err)
	}

	trashPath := filepath.Join(trashDir, fmt.Sprintf("%d-%s", time.Now().Unix(), album.Title))
	if err := os.Rename(album.Path, trashPath); err != nil {
		return false, fmt.Errorf("could not move folder to trash: %w", err)
	}

	if err := db.Delete(&models.Album{}, albumIDs(subtree)).Error; err != nil {
		// The rows are still there but the files are already in the trash;
		// surface the error rather than silently leaving stale DB rows.
		return false, fmt.Errorf("moved to trash, but failed to remove library entries: %w", err)
	}

	return true, nil
}
